
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;


SELECT * FROM MEMBER;

-- MEMBER 테이블에 INSERT 하기
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'a123@google.com', '1234', 'a1',
       '01012345678', '서울시 용산구', DEFAULT, DEFAULT);
      
COMMIT;

-- 로그인
SELECT MEMBER_NO, MEMBER_NICKNAME, MEMBER_TEL, MEMBER_ADDRESS,
	   TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS ') ENROLL_DATE
FROM MEMBER
WHERE MEMBER_EMAIL = 'a123@google.com'
AND MEMBER_PW = '123123'
AND MEMBER_DEL_FL = 'N';

-- 멤버 테이블 전체 조회
SELECT * FROM MEMBER
ORDER BY MEMBER_NO;

-- 닉네임, 전화 번호 수정

UPDATE MEMBER SET 
MEMBER_NICKNAME = '별명 ', 
MEMBER_TEL = '01012345678'
WHERE MEMBER_NO = '2';

-- 회원 탈퇴
UPDATE MEMBER SET 
MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 2
AND MEMBER_PW = 1234;

-- 보드 테이블에 INSERT 하기 
-- 실행 후 COMMIT/ROLLBACK 무조건 수행
INSERT INTO BOARD 
VALUES (SEQ_BOARD_NO.NEXTVAL, '제', '내', DEFAULT, DEFAULT, DEFAULT, 2);

SELECT BOARD_TITLE, BOARD_CONTENT, 
 TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS ') B_CREATE_DATE, 
 READ_COUNT, MEMBER_NO, MEMBER_NICKNAME 
FROM BOARD 
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_NO = 2
;

-- 조회수 증가
UPDATE BOARD SET 
READ_COUNT = READ_COUNT + 1
WHERE BOARD_NO = 1;

ROLLBACK;

SELECT 
FROM BOARD

SELECT * FROM MEMBER;
WHERE MEMBER_NO ='2'; 

SELECT * FROM BOARD;

DELETE FROM MEMBER
WHERE MEMBER_NO = '1';

-- 게시글 삭제
UPDATE  BOARD  SET 
BOARD_DEL_FL = 'Y'
WHERE BOARD_NO = '13';


